AirBnb_Proj:
  outputs:
    dev:
      account: JIZXJSE-AQ35392
      database: AIRBNB
      password: GulamGulam@de1
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: gulamhasande
      warehouse: COMPUTE_WH
  target: dev
airbnb_project:
  outputs:
    dev:
      account: JIZXJSE-AQ35392
      database: AIRBNB
      password: Gulam@de1
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: GulamHasan
      warehouse: COMPUTE_WH
  target: dev
